apiVersion: v1
kind: Service
metadata:
  name: mtlf-nmtlf
  labels:
    app: free5gc
    nf: nwdaf
    name: mtlf
spec:
  type: NodePort
  ports:
    - name: mtlf
      port: 8000
      nodePort: 30081
  selector:
    app: free5gc
    nf: nwdaf
    name: mtlf
