apiVersion: v1
kind: ConfigMap
metadata:
  name: nwdaf-mtlf-configmap
  labels:
    app: free5gc
data:
  nwdafcfg-mtlf.yaml: |
    info:
      version: 1.0.1
      description: NWDAF initial local configuration

    configuration:
      containerName: nwdaf-mtlf
      nwdafName: NWDAF # the name of this NWDAF
      
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: mtlf-nmtlf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 8000 # port used to bind the service

      serviceNameList: # the SBI services provided by this MTLF, refer to TS 29.518
        - nnwdaf-mlmodelprovision # Nnwdaf_MLModelProvision service
        - nnwdaf-mlmodelinfo # Nnwdaf_MLModelInfo service

      nrfUri: http://nrf-nnrf:8000 # a valid URI of NRF
      oamUri: http://prometheus-service:9090 # a valid URI of PCM (Packet Capture Module)

      networkName:  # the name of this core network
        full: free5GC
        short: free
      networkFeatureSupport5GS: # 5gs Network Feature Support IE, refer to TS 24.501
        enable: true # append this IE in Registration accept or not
        imsVoPS: 0 # IMS voice over PS session indicator (uinteger, range: 0~1)
        emc: 0 # Emergency service support indicator for 3GPP access (uinteger, range: 0~3)
        emf: 0 # Emergency service fallback indicator for 3GPP access (uinteger, range: 0~3)
        iwkN26: 0 # Interworking without N26 interface indicator (uinteger, range: 0~1)
        mpsi: 0 # MPS indicator (uinteger, range: 0~1)
        emcN3: 0 # Emergency service support indicator for Non-3GPP access (uinteger, range: 0~1)
        mcsi: 0 # MCS indicator (uinteger, range: 0~1)

    logger:
      NWDAF:
        debugLevel: info
        ReportCaller: false

  wrapper.sh: |
    #!/bin/bash

    # Cambiar al directorio deseado
    cd /free5gc/src/NFs/nwdaf-mtlf/ || { echo "Directorio no encontrado"; exit 1; }

    # Run mtlf
    air cmd/main.go
