apiVersion: v1
kind: ConfigMap
metadata:
  name: nwdaf-mtlf-configmap
  labels:
    app: free5gc
data:
  nwdafcfg-mtlf.yaml: |
    info:
      version: 1.0.0
      description: NWDAF initial local configuration

    configuration:
      containerName: nwdaf-mtlf
      name: nwdaf-mtlf
      nwdafName: NWDAF-MTLF # the name of this NWDAF
      
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: mtlf-nmtlf # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: 8000 # port used to bind the service

      serviceNameList: # the SBI services provided by this MTLF, refer to TS 29.518
        - nnwdaf-mlmodelprovision # Nnwdaf_MLModelProvision service
        - nnwdaf-mlmodelinfo # Nnwdaf_MLModelInfo service

      nrfUri: http://nrf-nnrf:8000 # a valid URI of NRF
      oamUri: http://prometheus-service.monitoring:8080 # a valid URI of PCM (Packet Capture Module)
      ksmInstance: "kube-state-metrics.kube-system.svc.cluster.local:8080" # a valid kube-state-metrics instance
      namespace: "free5gc" # namespace of 5GC

      mlModelTrainingInfo:
        timeSteps: 4 # a valida int to time series

      sqlLiteDB: ml_model_info.db # a valid PATH of the SqlLite

      networkName:  # the name of this core network
        full: free5GC
        short: free

    logger:
      NWDAF:
        debugLevel: info
        ReportCaller: false

  wrapper.sh: |
    #!/bin/bash

    ./nwdaf-mtlf --config config/nwdafcfg-mtlf.yaml
