apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf
  labels:
    app: free5gc
    nf: amf
    name: amf
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: amf
      name: amf
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: amf
        name: amf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network", "interface": "n2", "ips": [ "10.10.2.2/24" ] }
          ]'
    spec:
      initContainers:
      - name: wait-nrf
        image: appropriate/curl
        command: ['sh', '-c', 'until curl -s -o /dev/null -w "%{http_code}" http://nrf-nnrf:8000 | grep "200"; do sleep 1; done;']
      containers:
      - image: edierbra/free5gc-dev:v3.2.5.5
        imagePullPolicy: Always
        name: amf1
        ports:
        - name: namf
          containerPort: 8000
        - name: n2
          containerPort: 38412
          protocol: SCTP
        command: ["/bin/sh", "-c"]
        args: ["cd ./src/NFs/amf && air"]
        # command: ["./amf"]
        # args: ["--config", "config/amfcfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /root/go/
          name: go-path-volume
        - mountPath: /free5gc/src/
          name: free5gc-vanilla-volume
        - mountPath: /free5gc/src/NFs/amf/config/
          name: amf-volume
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: amf-volume
        projected:
          sources:
          - configMap:
              name: amf-configmap
      - name: free5gc-vanilla-volume
        persistentVolumeClaim:
          claimName: free5gc-vanilla-volume-claim
      - name: go-path-volume
        persistentVolumeClaim:
          claimName: go-path-volume-claim
