apiVersion: v1
kind: Service
metadata:
  name: anlf-nanlf
  labels:
    app: free5gc
    nf: nwdaf
    name: anlf
spec:
  type: NodePort
  ports:
    - name: nwdaf
      port: 8000
    - name: openapi 
      port: 8080
      nodePort: 30080
  selector:
    app: free5gc
    nf: nwdaf
    name: anlf

# Open your browser to here: http://localhost:30080/nnwdaf-analyticsinfo/v1/ui/
# Your OpenAPI definition lives here: http://localhost:30080/nnwdaf-analyticsinfo/v1/openapi.json
# To launch the integration tests, use tox: sudo pip install tox; tox
