apiVersion: v1
kind: Service
metadata:
  name: anlf-nanlf
  labels:
    app: free5gc
    nf: nwdaf
    name: anlf
spec:
  type: NodePort
  ports:
    - name: nwdaf
      port: 8000
      nodePort: 30080
  selector:
    app: free5gc
    nf: nwdaf
    name: anlf
    