apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-vanilla-volume
  labels:
    app: vanilla
spec:
  capacity:
    storage: 5Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # path: "/home/jnicolaschc/Development/TrabajoGrado_restored/free5gc-vanilla/"
    # path: "/home/edier/Tesis/5g-monarch2/free5gc-vanilla/"
    # path: "/vagrant-data/free5gc-vanilla/"
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-volume
  labels:
    app: nas
spec:
  capacity:
    storage: 5Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # path: "/home/jnicolaschc/Development/TrabajoGrado_restored/nas/"
    # path: "/home/edier/Tesis/5g-monarch2/nas/"
    # path: "/vagrant-data/nas/"
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ngap-volume
  labels:
    app: ngap
spec:
  capacity:
    storage: 5Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # path: "/home/jnicolaschc/Development/TrabajoGrado_restored/ngap/"
    # path: "/home/edier/Tesis/5g-monarch2/ngap/"
    # path: "/vagrant-data/ngap/"
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openapi-volume
  labels:
    app: openapi
spec:
  capacity:
    storage: 5Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # path: "/home/jnicolaschc/Development/TrabajoGrado_restored/openapi/"
    # path: "/home/edier/Tesis/5g-monarch2/openapi/"
    # path: "/vagrant-data/openapi/"
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-path-volume
  labels:
    app: gopath
spec:
  capacity:
    storage: 5Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # path: "/home/jnicolaschc/go/"
    # path: "/home/edier/go/"
    # path: "/home/vagrant/go/"
    type: Directory
