---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue123
  labels:
    app: ueransim
    component: ue
    name: ue123
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue123
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue123
    spec:
      containers:
      - image: edierbra/ueransim:v3.2.6-1
        imagePullPolicy: IfNotPresent
        name: ue123
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/bin/bash", "-c", "--" ]
        args:
          - |
            if [ "$DEBUG_MODE" = "true" ]; then
              while true; do sleep 30; done;
            else
              /ueransim/config/wrapper.sh
            fi
        env:
          - name: DEBUG_MODE
            value: "false"
        volumeMounts:
        - mountPath: /ueransim/config
          name: ue123-volume
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "16Mi"
            cpu: "10m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ue123-volume
          projected:
            sources:
              - configMap:
                  name: ue123-configmap
                  items:
                    - key: ue.yaml
                      path: ue.yaml
                    - key: wrapper.sh
                      path: wrapper.sh
                      mode: 0755
              - configMap:
                  name: ue-iptables-configmap
                  items:
                    - key: ue-iptables.sh
                      path: ue-iptables.sh
                      mode: 0755
          