FROM gcc:9.4.0 AS builder

LABEL maintainer="EN <example.en@gmail.com>"
LABEL description="UERANSIM v3.2.6-ditg"

ENV DEBIAN_FRONTEND noninteractive

# Install dependencies
RUN apt-get update \
    && apt-get install libsctp-dev lksctp-tools iproute2 zip -y \
    && wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.sh -O cmake_installer.sh \
    && chmod +x cmake_installer.sh \
    && ./cmake_installer.sh --skip-license \
    && git clone -b v3.2.6 -j `nproc` https://github.com/aligungr/UERANSIM \
    && cd ./UERANSIM \
    && make \
    && mkdir /D-ITG \
    && wget https://traffic.comics.unina.it/software/ITG/codice/D-ITG-2.8.1-r1023-src.zip -O /D-ITG/D-ITG.zip \
    && cd /D-ITG \
    && unzip D-ITG.zip \
    && cd ./D-ITG-2.8.1-r1023/src \
    && make

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

# Install runtime dependencies + debug tools
RUN apt-get update \
    && apt-get -y install libsctp-dev lksctp-tools iproute2 iputils-ping \
    && apt-get -y install vim iperf3 net-tools tcpdump zip build-essential wget\
    && apt-get clean

WORKDIR /ueransim

RUN mkdir -p config/ binder/ D-ITG/

COPY /tun/* ./
RUN chmod +x init.sh

COPY --from=builder /UERANSIM/build/nr-gnb .
COPY --from=builder /UERANSIM/build/nr-ue .
COPY --from=builder /UERANSIM/build/nr-cli .
COPY --from=builder /UERANSIM/build/nr-binder binder/
COPY --from=builder /UERANSIM/build/libdevbnd.so binder/
COPY --from=builder /D-ITG/D-ITG-2.8.1-r1023/bin/* D-ITG/

VOLUME [ "/ueransim/config" ]