apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-smf2
  labels:
    app: free5gc
    nf: smf
    name: smf2
spec:
  selector:
    matchLabels:
      app: free5gc
      nf: smf
      name: smf2
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc
        nf: smf
        name: smf2
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n4network", "interface": "n4", "ips": [ "10.10.4.102/24" ] }
          ]'
    spec:
      initContainers:
      - name: wait-ausf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: ausf-nausf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AUSF; sleep 2; done;"]
      containers:
      - image: edierbra/free5gc-dev:v3.2.5.8 # edierbra/free5gc-dev:v3.2.5.7
        name: smf2
        imagePullPolicy: Always
        ports:
        - name: nsmf
          containerPort: 8000
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        command: ["/bin/sh", "-c"]
        args: ["cd ./src/NFs/smf && air"]
        # command: ["./smf"]
        # args: ["--config", "config/smfcfg.yaml"]   
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /root/go/
          name: go-path-volume
        - mountPath: /free5gc/src/
          name: free5gc-vanilla-volume
        - mountPath: /free5gc/src/NFs/smf/config/
          name: smf-volume
        - mountPath: /free5gc/nas/
          name: nas-volume
        - mountPath: /free5gc/ngap/
          name: ngap-volume
        - mountPath: /free5gc/openapi/
          name: openapi-volume
        # resources:
        #   requests:
        #     memory: "100Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: smf-volume
        projected:
          sources:
          - configMap:
              name: smf2-configmap
              items:
              - key: smfcfg.yaml
                path: smfcfg.yaml
              - key: uerouting.yaml
                path: uerouting.yaml
      - name: free5gc-vanilla-volume
        persistentVolumeClaim:
          claimName: free5gc-vanilla-volume-claim
      - name: nas-volume
        persistentVolumeClaim:
          claimName: nas-volume-claim
      - name: ngap-volume
        persistentVolumeClaim:
          claimName: ngap-volume-claim
      - name: go-path-volume
        persistentVolumeClaim:
          claimName: go-path-volume-claim
      - name: openapi-volume
        persistentVolumeClaim:
          claimName: openapi-volume-claim
