apiVersion: v1
kind: Service
metadata:
  name: nrf-nnrf
  labels:
    app: free5gc
    nf: nrf
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30088
  selector:
    app: free5gc
    nf: nrf
