apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: models-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: nwdaf
      name: models