apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-vanilla-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/Tesis/5g-monarch2/free5gc-vanilla"
  persistentVolumeReclaimPolicy: Retain