apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: container-1
        image: ubuntu:20.04
        command: ["/bin/sh", "-c"]
        args: ["sleep infinity"]
        volumeMounts:
        - mountPath: /root/go/
          name: volume2
        - mountPath: /root/vanilla/
          name: volume1
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: volume1-claim
      - name: volume2
        persistentVolumeClaim:
          claimName: volume2-claim