---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue3
  labels:
    app: ueransim
    component: ue
    name: ue3
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue3
  replicas: 
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue3
    spec:
      containers:
      - image: edierbra/ueransim:v3.2.6
        imagePullPolicy: Always
        name: ue
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: [ "/bin/bash", "-c", "--" ]
        args:
          - |
            if [ "$DEBUG_MODE" = "true" ]; then
              while true; do sleep 30; done;
            else
              /ueransim/config/wrapper.sh
            fi
        env:
          - name: DEBUG_MODE
            value: "false"
        volumeMounts:
        - mountPath: /ueransim/config
          name: ue3-volume
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: ue3-volume
        configMap:
          name: ue3-configmap
          items:
          - key: ue3.yaml
            path: ue3.yaml
          - key: wrapper.sh
            path: wrapper.sh
            mode: 0755