---
apiVersion: v1
kind: Service
metadata:
  namespace: grafana
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - name: service
    port: 3000
    nodePort: 30300
    protocol: TCP
  selector:
    app: grafana
