apiVersion: v1
kind: Service
metadata:
  name: nwdaf-nnwdaf
  labels:
    app: free5gc
    nf: nwdaf
    name: module1
spec:
  type: NodePort
  ports:
    - name: nwdaf
      port: 8000
      nodePort: 30081
  selector:
    app: free5gc
    nf: nwdaf
    name: module1