apiVersion: v1
kind: PersistentVolume
metadata:
  name: ueransim-volume
  labels:
    app: ueransim
    name: gnb
spec:
  capacity:
    storage: 2Gi # Ajusta el tamaño según tus necesidades
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    # path: "/home/jnicolaschc/Development/TrabajoGrado_restored/ueransim/build/"
    # path: "/vagrant-data/ueransim/build/" 
    path: "/home/edier/Tesis/5g-monarch2/ueransim/build/"
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ueransim-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: ueransim
      name: gnb
